image: java:8-jdk

stages:
- build

before_script:
- export GRADLE_USER_HOME=$(pwd)/.gradle
- chmod +x ./gradlew
- chmod +x ./ktlint

cache:
  key: ${CI_PROJECT_ID}
  paths:
  - .gradle/

build:
  stage: build
  script:
  - ./gradlew build
  - ./ktlint --reporter=plain --reporter=checkstyle,output=ktlint-report.xml
  - echo "Code Size"
  - find src/main \( -name '*.java' -or -name '*.kt' \) | xargs wc -l | tail -1
  artifacts:
    paths:
    - build/distributions/*.*
    - build/libs/*.*
    - ktlint-report.xml