image: java:8-jdk

stages:
- build
- lint

before_script:
- export GRADLE_USER_HOME=$(pwd)/.gradle
- chmod +x ./gradlew
- chmod +x ./ktlint

cache:
  key: ${CI_PROJECT_ID}
  paths:
  - .gradle/

after_script:
- echo "Code Size"
- find src/main \( -name '*.java' -or -name '*.kt' \) | xargs wc -l | tail -1

build:
  stage: build
  script:
  - ./gradlew build
  artifacts:
    paths:
    - build/distributions/*.*
    - build/libs/*.*

lint:
  stage: lint
  script:
  - ./ktlint --reporter=plain --reporter=checkstyle,output=ktlint-report-in-checkstyle-format.xml
